version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pollo
      - POSTGRES_PASSWORD=pollo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9898:8080
